### ISSUE TITLE
pre installation query

### ISSUE THREAD

**Issue by Aeres-u99** [DebianJoe/nullWM#3]
Just felt like asking, will it show up and allow me to change wm in lightdm? or will I be stuck in nullWM forever. 
Just curious, will something like this work for it? 

```
If you compiled and installed dwm from source keeping the defaults, its executable has to be in /usr/local/bin/.

In this case you have to create a new .desktop file in /usr/share/xsessions/ using the command

sudo nano /usr/share/xsessions/dwm.desktop

and paste the following content in it:

[Desktop Entry]
Encoding=UTF-8
Name=dwm
Comment=dwm window manager
Exec=/usr/local/bin/dwm
Type=Application

Save the file using Ctrl+o and exit using Ctrl+x.

Then all you have to do is logout and choose dwm for your session in your display manager.

```

**Comment by DebianJoe** [comment]
Feel free to try whatever you like.  I wrote that mostly as an experiment
in minimalism and have not even glanced at the code in years.  It will
either work, or not.

- DJ

**Comment by Aeres-u99** [comment]
Nice :-) I am thinking of making few changes, its a really nice idea btw. Thanks.

**Comment by Aeres-u99** [comment]
And for those who are wondering, the .desktop method works well, with lightdm. The format may change depending upon OS.
